version: '3.7'

services:
  geteway:
    build:
      context: ./docker/dev/gateway/nginx
    restart: always
    ports:
      - '8001:8001'
      - '8002:8002'
    depends_on:
      - frontend-nginx
      - backend-nginx

  frontend-nginx:
    build:
      context: ./docker/dev/frontend/nginx
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - frontend-php-fpm
      - postgres

  frontend-php-fpm:
    build:
      context: ./docker/dev/frontend/php-fpm
    restart: always
    volumes:
      - ./:/app

  backend-nginx:
    build:
      context: ./docker/dev/backend/nginx
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - backend-php-fpm
      - postgres

  backend-php-fpm:
    build:
      context: ./docker/dev/backend/php-fpm
    restart: always
    volumes:
      - ./:/app

  postgres:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - ./docker/dev/postgres/data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
