version: '3.7'

services:
  geteway:
    build:
      context: ./docker/gateway/docker/dev/nginx
    restart: always
    ports:
      - '8001:8001'
      - '8002:8002'
    depends_on:
      - frontend-nginx
      - backend-nginx

  frontend-nginx:
    build:
      context: ./docker/frontend/dev/nginx
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - php-fpm

  backend-nginx:
    build:
      context: ./docker/backend/dev/nginx
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/common/dev/php-fpm
    restart: always
    volumes:
      - ./:/app

  php-cli:
    build:
      context: ./docker/common/dev/php-cli
    volumes:
      - ./:/app
